version: "3.9"
services:
  app:
    container_name: laravel-ownership-app
    image: laravel-ownership-app
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - laravel-ownership

  nginx:
    container_name: laravel-ownership-nginx
    image: nginx:1.21-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: app.laravel-ownership.localhost
    volumes:
      - ./.docker/nginx/app.laravel-ownership.80.conf:/etc/nginx/conf.d/app.laravel-ownership.80.conf:ro
      - ./public:/app/public:ro
    networks:
      - laravel-ownership

networks:
  laravel-ownership:
    driver: bridge
